language: ruby
cache: bundler
rvm:
  - 2.6.2
  - 2.5.5
  - 2.4.5
  - 2.3.8
  - jruby-9.1.16.0
gemfile:
  - gemfiles/rails5.gemfile
matrix:
  fast_finish: true
env:
  global:
    - JRUBY_OPTS='--debug'
script:
  - bundle exec rake
before_install:
  - gem install bundler
  - sudo apt-get -y remove memcached
  - sudo apt-get install libevent-dev
  - wget https://memcached.org/files/memcached-1.5.20.tar.gz
  - tar -zxvf memcached-1.5.20.tar.gz
  - cd memcached-1.5.20
  - ./configure --enable-sasl
  - make
  - sudo make install
