language: ruby
cache: bundler
rvm:
  - ruby-head
  - 2.5.0
  - 2.4.3
  - 2.3.6
  - 2.2.9
  - 2.1.10
  - 2.0.0
  - 1.9.3
  - rbx-2
  - jruby
  - jruby-9.0.4.0
gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails4.gemfile
  - gemfiles/rails5.gemfile
matrix:
  exclude:
    - rvm: 2.1.8
      gemfile: gemfiles/rails5.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails5.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails5.gemfile
    - rvm: rbx-2
      gemfile: gemfiles/rails5.gemfile
    - rvm: jruby
      gemfile: gemfiles/rails5.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails4.gemfile
    - rvm: jruby
      gemfile: gemfiles/rails4.gemfile
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
  fast_finish: true
env: JRUBY_OPTS='--1.9'
script:
  - bundle exec rake
before_install:
  - gem install bundler
  - sudo apt-get -y remove memcached
  - sudo apt-get install libevent-dev
  - wget https://memcached.org/files/memcached-1.4.15.tar.gz
  - tar -zxvf memcached-1.4.15.tar.gz
  - cd memcached-1.4.15
  - ./configure --enable-sasl
  - make
  - sudo make install
