name: Profiles

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Install Memcached 1.6.23
      working-directory: scripts
      env:
        MEMCACHED_VERSION: 1.6.23
      run: |
        chmod +x ./install_memcached.sh
        ./install_memcached.sh
        memcached -d
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4
        bundler-cache: true # 'bundle install' and cache
    - name: Run Profiles
      run: RUBY_YJIT_ENABLE=1 BENCH_TARGET=all bundle exec bin/profile
    # NOTE: to pull profile results, visit https://github.com/petergoldstein/dalli/actions/workflows/profile.yml
    # click to view the run you are interested in (ex https://github.com/petergoldstein/dalli/actions/runs/13296952241)
    # in the artifacts section, download the profile results
    - name: Upload profile results
      uses: actions/upload-artifact@v6
      with:
        name: profile-results
        path: |
          client_get_profile.json
          socket_get_profile.json
          client_set_profile.json
          socket_set_profile.json
          client_get_multi_profile.json
          socket_get_multi_profile.json
          client_set_multi_profile.json
          socket_set_multi_profile.json
          meta_client_get_multi_profile.json
          meta_client_get_profile.json
          meta_client_set_multi_profile.json
          meta_client_set_profile.json
