name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - head
          - '4.0'
          - '3.4'
          - '3.3'
          - '3.2'
          - '3.1'
          - jruby-10
          - truffleruby
        memcached-version: ['1.5.22', '1.6.40']

    name: "Ruby ${{ matrix.ruby-version }} / Memcached ${{ matrix.memcached-version }}"
    steps:
    - uses: actions/checkout@v6
    - name: Install Memcached ${{ matrix.memcached-version }}
      working-directory: scripts
      env:
        MEMCACHED_VERSION: ${{ matrix.memcached-version }}
      run: |
        chmod +x ./install_memcached.sh
        ./install_memcached.sh
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # 'bundle install' and cache
    - name: Run tests
      run: bundle exec rake
      env:
        RUN_SASL_TESTS: 1
