name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [2.5, 2.6, 2.7, '3.0', jruby-9.2, jruby-9.3]
        memcached-version: ['1.5.22', '1.6.12', '1.4.39']

    steps:
    - uses: actions/checkout@v2
    - name: Install Memcached ${{ matrix.memcached-version }}
      working-directory: scripts
      env:
        MEMCACHED_VERSION: ${{ matrix.memcached-version }}
      run: |
        chmod +x ./install_memcached.sh
        ./install_memcached.sh
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # 'bundle install' and cache
    - name: Run tests
      run: bundle exec rake
